### ISSUE TITLE
prev/next looks inverted

### ISSUE THREAD

**Issue by glihm** [lambdaclass/cairo-by-example#67]
When browsing the examples on the currently deployed version, the `prev/next` look inverted. I am not familiar with the framework, is that something expected?

`Hello world` is the first of the list, and only prev is available.

![image](https://github.com/lambdaclass/cairo-by-example/assets/7962849/ddf07907-12bd-4360-a290-64d1cdd5420d)

**Comment by rcatalan98** [comment]
Closed by #80
